allowBuilds:
  electron: true
  esbuild: true
onlyBuiltDependencies:
  - ','
  - /
  - '3'
  - '@'
  - a
  - b
  - c
  - d
  - e
  - electron
  - esbuild
  - f
  - h
  - i
  - k
  - l
  - n
  - o
  - q
  - r
  - s
  - t
  - u
