name: project-space

services:
  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    environment:
      PROJECT_CONNECTOR_SERVICE_NAME: project-space-web
    image: project-space-web:local
    restart: unless-stopped

  docs:
    build:
      context: ..
      dockerfile: apps/docs/Dockerfile
    image: project-space-docs:local
    restart: unless-stopped
