host: deploy@100.84.238.75
preview:
  statusHost: project-space-preview-status
secrets:
  CLERK_PUBLISHABLE_KEY: op://projects/clerk-project/publishable_key
  CLERK_SECRET_KEY: op://projects/clerk-project/secret_key
  GITHUB_OAUTH_CLIENT_ID: op://projects/GitHub OAuth App/client_id
  GITHUB_TOKEN: op://projects/GitHub Personal Access Token/token
  PROJECT_CONNECTOR_REGISTRATION_TOKEN: op://projects/Project Space Connector Registration Token/password
  PROJECT_CONNECTOR_COMMAND_SIGNING_PRIVATE_KEY_B64: op://projects/project-connector-command-signing-key/private_key_b64
  PROJECT_RELEASE_MANIFEST_SIGNING_PUBLIC_KEY_B64: op://projects/project-space-release-manifest-signing-key/public_key_b64
  PROJECT_SPACE_MACHINE_RATE_LIMIT_SECRET: op://projects/project-space-machine-rate-limit/password
  PROJECT_SPACE_MACHINE_POWER_MQTT_JETKVM_B46E1A936AC89A4E_PASSWORD: op://projects/project-space-mqtt-jetkvm-b46e1a936ac89a4e-client/password
  PROJECT_SPACE_MACHINE_POWER_MQTT_JETKVM_B46E1A936AC89A4E_USERNAME: op://projects/project-space-mqtt-jetkvm-b46e1a936ac89a4e-client/username
  VITE_CLERK_PUBLISHABLE_KEY: op://projects/clerk-project/publishable_key
environments:
  prod:
    default: true
    branch: main
    path: /opt/platform/apps/project-space
    domain: projects.os-home.net
    apiDomain: api.projects.os-home.net
  beta:
    branch: beta
    path: /opt/platform/apps/project-space-beta
    domain: beta.projects.os-home.net
    apiDomain: api.beta.projects.os-home.net
