host: deploy@100.84.238.75
preview:
  statusHost: project-space-preview-status
secrets:
  CLERK_PUBLISHABLE_KEY: infisical://467bbc88-262a-4ea0-a238-9666d6e7e359/prod/CLERK_PUBLISHABLE_KEY
  CLERK_SECRET_KEY: infisical://467bbc88-262a-4ea0-a238-9666d6e7e359/prod/CLERK_SECRET_KEY
  GITHUB_OAUTH_CLIENT_ID: infisical://467bbc88-262a-4ea0-a238-9666d6e7e359/prod/GITHUB_OAUTH_CLIENT_ID
  PROJECT_RELEASE_MANIFEST_SIGNING_PUBLIC_KEY_B64: infisical://467bbc88-262a-4ea0-a238-9666d6e7e359/prod/PROJECT_RELEASE_MANIFEST_SIGNING_PUBLIC_KEY_B64
  PROJECT_SPACE_MACHINE_RATE_LIMIT_SECRET: infisical://467bbc88-262a-4ea0-a238-9666d6e7e359/prod/PROJECT_SPACE_MACHINE_RATE_LIMIT_SECRET
  PROJECT_SPACE_TOKEN_ENCRYPTION_KEY: infisical://467bbc88-262a-4ea0-a238-9666d6e7e359/prod/PROJECT_SPACE_TOKEN_ENCRYPTION_KEY
  PROJECT_SPACE_MACHINE_POWER_MQTT_JETKVM_B46E1A936AC89A4E_PASSWORD: infisical://467bbc88-262a-4ea0-a238-9666d6e7e359/prod/PROJECT_SPACE_MACHINE_POWER_MQTT_JETKVM_B46E1A936AC89A4E_PASSWORD
  PROJECT_SPACE_MACHINE_POWER_MQTT_JETKVM_B46E1A936AC89A4E_USERNAME: infisical://467bbc88-262a-4ea0-a238-9666d6e7e359/prod/PROJECT_SPACE_MACHINE_POWER_MQTT_JETKVM_B46E1A936AC89A4E_USERNAME
  VITE_CLERK_PUBLISHABLE_KEY: infisical://467bbc88-262a-4ea0-a238-9666d6e7e359/prod/VITE_CLERK_PUBLISHABLE_KEY
environments:
  prod:
    default: true
    branch: main
    path: /opt/platform/apps/project-space
    domain: projects.os-home.net
    apiDomain: api.projects.os-home.net
  beta:
    branch: beta
    path: /opt/platform/apps/project-space-beta
    domain: beta.projects.os-home.net
    apiDomain: api.beta.projects.os-home.net
