package main

import (
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

const cliDocsSchemaVersion = 1

type cliDocsModel struct {
	SchemaVersion      int            `json:"schemaVersion"`
	DocumentationTrack string         `json:"documentationTrack"`
	PlatformScope      string         `json:"platformScope"`
	Root               cliDocsCommand `json:"root"`
}

type cliDocsCommand struct {
	Path     string           `json:"path"`
	Name     string           `json:"name"`
	Usage    string           `json:"usage"`
	Short    string           `json:"short"`
	Aliases  []string         `json:"aliases"`
	Runnable bool             `json:"runnable"`
	Flags    []cliDocsFlag    `json:"flags"`
	Commands []cliDocsCommand `json:"commands"`
}

type cliDocsFlag struct {
	Name        string `json:"name"`
	Shorthand   string `json:"shorthand,omitempty"`
	Type        string `json:"type"`
	Description string `json:"description"`
	Inherited   bool   `json:"inherited"`
}

func newCLIDocsCommand() *cobra.Command {
	format := "json"
	command := &cobra.Command{
		Use:    "__docs-model",
		Hidden: true,
		Args:   cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			model := buildCLIDocsModel(cmd.Root())
			switch format {
			case "json":
				return encodeCLIDocsModel(cmd.OutOrStdout(), model)
			case "mdx":
				return renderCLIDocsMDX(cmd.OutOrStdout(), model)
			default:
				return fmt.Errorf("unknown docs format %q; use json or mdx", format)
			}
		},
	}
	command.Flags().StringVar(&format, "format", "json", "generated output format: json or mdx")
	return command
}

func buildCLIDocsModel(root *cobra.Command) cliDocsModel {
	root.InitDefaultHelpCmd()
	root.InitDefaultCompletionCmd()
	root.InitDefaultVersionFlag()
	return cliDocsModel{
		SchemaVersion:      cliDocsSchemaVersion,
		DocumentationTrack: "current-main-source",
		PlatformScope:      "managed-macos-linux-wsl",
		Root:               buildCLIDocsCommand(root),
	}
}

func buildCLIDocsCommand(command *cobra.Command) cliDocsCommand {
	command.InitDefaultHelpFlag()
	aliases := append([]string{}, command.Aliases...)
	sort.Strings(aliases)
	result := cliDocsCommand{
		Path:     command.CommandPath(),
		Name:     command.Name(),
		Usage:    strings.TrimSpace(command.Use),
		Short:    strings.TrimSpace(command.Short),
		Aliases:  aliases,
		Runnable: command.Runnable(),
		Flags:    collectCLIDocsFlags(command),
		Commands: []cliDocsCommand{},
	}
	children := append([]*cobra.Command(nil), command.Commands()...)
	sort.Slice(children, func(i, j int) bool { return children[i].Name() < children[j].Name() })
	for _, child := range children {
		if child.Hidden || child.Deprecated != "" {
			continue
		}
		result.Commands = append(result.Commands, buildCLIDocsCommand(child))
	}
	return result
}

func collectCLIDocsFlags(command *cobra.Command) []cliDocsFlag {
	flags := make([]cliDocsFlag, 0)
	seen := make(map[string]struct{})
	appendFlags := func(flagSet *pflag.FlagSet, inherited bool) {
		flagSet.VisitAll(func(flag *pflag.Flag) {
			if flag.Hidden {
				return
			}
			if _, exists := seen[flag.Name]; exists {
				return
			}
			seen[flag.Name] = struct{}{}
			flags = append(flags, cliDocsFlag{
				Name:        flag.Name,
				Shorthand:   flag.Shorthand,
				Type:        flag.Value.Type(),
				Description: strings.TrimSpace(flag.Usage),
				Inherited:   inherited,
			})
		})
	}
	appendFlags(command.NonInheritedFlags(), false)
	appendFlags(command.InheritedFlags(), true)
	sort.Slice(flags, func(i, j int) bool { return flags[i].Name < flags[j].Name })
	return flags
}

func encodeCLIDocsModel(writer io.Writer, model cliDocsModel) error {
	encoder := json.NewEncoder(writer)
	encoder.SetEscapeHTML(false)
	encoder.SetIndent("", "  ")
	return encoder.Encode(model)
}

func renderCLIDocsMDX(writer io.Writer, model cliDocsModel) error {
	lines := []string{
		"---",
		"title: CLI",
		"description: Generated command reference for the Project CLI.",
		"---",
		"",
		"{/* Generated by `bun run docs:cli:generate`. Do not edit this file by hand. */}",
		"",
		"> **Documentation track:** current `main` source. This reference can be ahead of the latest published binary. Check `project --version` and the [latest GitHub release](https://github.com/DotNaos/project-space/releases/latest) before assuming a command is installed.",
		"",
		"> Flag details cover managed macOS, Linux, and WSL installations. The native Windows CLI delegates runtime commands to WSL and can expose a smaller guidance-only flag surface.",
		"",
		"This page is generated from the same Cobra command tree used by the `project` binary.",
		"",
		"## Base Command",
		"",
		"```sh",
		model.Root.Usage,
		"```",
		"",
	}
	lines = append(lines, renderCLIDocsFlags(model.Root.Flags)...)
	lines = append(lines, "## Commands", "", "| Command | Aliases | Description |", "| --- | --- | --- |")
	for _, command := range model.Root.Commands {
		lines = append(lines, fmt.Sprintf("| [`%s`](#%s) | %s | %s |", command.Name, commandAnchor(command.Path), renderAliases(command.Aliases), escapeMarkdownTable(command.Short)))
	}
	lines = append(lines, "", "## Command Reference", "")
	for _, command := range model.Root.Commands {
		lines = append(lines, renderCLIDocsCommand(command)...)
	}
	lines = append(lines,
		"## Guides", "",
		"- [Project Doctor](/docs/cli/doctor)",
		"- [Self-update](/docs/cli/self-update)",
		"- [Create and init](/docs/cli/create-init)",
		"- [Validate](/docs/cli/validate)",
		"- [Modules](/docs/cli/modules)",
		"- [Template commands](/docs/cli/template)",
		"- [Deploy](/docs/cli/deploy)",
		"- [Shell completion](/docs/cli/completion)",
		"",
	)
	_, err := io.WriteString(writer, strings.Join(lines, "\n"))
	return err
}

func renderCLIDocsCommand(command cliDocsCommand) []string {
	lines := []string{
		fmt.Sprintf("<h3 id=\"%s\" className=\"scroll-m-28\"><code>%s</code></h3>", commandAnchor(command.Path), command.Path),
		"",
		command.Short,
		"",
		"```sh",
		command.Path[:len(command.Path)-len(command.Name)] + command.Usage,
		"```",
		"",
	}
	if len(command.Aliases) > 0 {
		lines = append(lines, "Aliases: "+renderAliases(command.Aliases), "")
	}
	lines = append(lines, renderCLIDocsFlags(command.Flags)...)
	for _, child := range command.Commands {
		lines = append(lines, renderCLIDocsCommand(child)...)
	}
	return lines
}

func commandAnchor(path string) string {
	return strings.ReplaceAll(path, " ", "-")
}

func renderCLIDocsFlags(flags []cliDocsFlag) []string {
	if len(flags) == 0 {
		return nil
	}
	lines := []string{"| Flag | Type | Scope | Description |", "| --- | --- | --- | --- |"}
	for _, flag := range flags {
		name := "`--" + flag.Name + "`"
		if flag.Shorthand != "" {
			name = "`-" + flag.Shorthand + "`, " + name
		}
		scope := "local"
		if flag.Inherited {
			scope = "inherited"
		}
		lines = append(lines, fmt.Sprintf("| %s | `%s` | %s | %s |", name, flag.Type, scope, escapeMarkdownTable(flag.Description)))
	}
	return append(lines, "")
}

func renderAliases(aliases []string) string {
	if len(aliases) == 0 {
		return "-"
	}
	formatted := make([]string, 0, len(aliases))
	for _, alias := range aliases {
		formatted = append(formatted, "`"+alias+"`")
	}
	return strings.Join(formatted, ", ")
}

func escapeMarkdownTable(value string) string {
	value = strings.ReplaceAll(value, "|", "\\|")
	value = strings.ReplaceAll(value, "\n", " ")
	return value
}
