export const projectChatNameCatalog = [
  ['athena', 'Athena', 'mythology'],
  ['hermes', 'Hermes', 'mythology'],
  ['nyx', 'Nyx', 'mythology'],
  ['apollo', 'Apollo', 'mythology'],
  ['artemis', 'Artemis', 'mythology'],
  ['ares', 'Ares', 'mythology'],
  ['hera', 'Hera', 'mythology'],
  ['hestia', 'Hestia', 'mythology'],
  ['demeter', 'Demeter', 'mythology'],
  ['persephone', 'Persephone', 'mythology'],
  ['selene', 'Selene', 'mythology'],
  ['helios', 'Helios', 'mythology'],
  ['eos', 'Eos', 'mythology'],
  ['iris', 'Iris', 'mythology'],
  ['nike', 'Nike', 'mythology'],
  ['themis', 'Themis', 'mythology'],
  ['nemesis', 'Nemesis', 'mythology'],
  ['hecate', 'Hecate', 'mythology'],
  ['pan', 'Pan', 'mythology'],
  ['orpheus', 'Orpheus', 'mythology'],
  ['theseus', 'Theseus', 'mythology'],
  ['perseus', 'Perseus', 'mythology'],
  ['ariadne', 'Ariadne', 'mythology'],
  ['echo', 'Echo', 'mythology'],
  ['gaia', 'Gaia', 'mythology'],
  ['rhea', 'Rhea', 'mythology'],
  ['maia', 'Maia', 'mythology'],
  ['metis', 'Metis', 'mythology'],
  ['clio', 'Clio', 'mythology'],
  ['thalia', 'Thalia', 'mythology'],
  ['calliope', 'Calliope', 'mythology'],
  ['erato', 'Erato', 'mythology'],
  ['urania', 'Urania', 'mythology'],
  ['circe', 'Circe', 'mythology'],
  ['calypso', 'Calypso', 'mythology'],
  ['hypnos', 'Hypnos', 'mythology'],
  ['morpheus', 'Morpheus', 'mythology'],
  ['triton', 'Triton', 'mythology'],
  ['atlas', 'Atlas', 'mythology'],
  ['janus', 'Janus', 'mythology'],
  ['aurora', 'Aurora', 'mythology'],
  ['luna', 'Luna', 'mythology'],
  ['flora', 'Flora', 'mythology'],
  ['minerva', 'Minerva', 'mythology'],
  ['vesta', 'Vesta', 'mythology'],
  ['diana', 'Diana', 'mythology'],
  ['mercury', 'Mercury', 'mythology'],
  ['juno', 'Juno', 'mythology'],
  ['picasso', 'Picasso', 'artist'],
  ['mondrian', 'Mondrian', 'artist'],
  ['rams', 'Rams', 'artist'],
  ['turing', 'Turing', 'science'],
  ['curie', 'Curie', 'science'],
  ['euler', 'Euler', 'science'],
  ['holmes', 'Holmes', 'detective'],
  ['poirot', 'Poirot', 'detective'],
  ['marple', 'Marple', 'detective']
] as const;

export type ProjectChatNameCategory = typeof projectChatNameCatalog[number][2];
export const reservedProjectChatNames = new Set(['poirot']);

export function findProjectChatName(value: string) {
  const key = value.normalize('NFKC').trim().toLocaleLowerCase('en-US');
  return projectChatNameCatalog.find(([candidate]) => candidate === key);
}
